CREATE  TABLE "AUTHORIZED" (
    "TAG_ID" VARCHAR PRIMARY KEY  NOT NULL 
);

CREATE TABLE "PASS" (
    "ID" INTEGER PRIMARY KEY  NOT NULL,
    "TAG_ID" VARCHAR NOT NULL,
    "PASS_TIME" INTEGER NOT NULL, 
    "BARRIER_ID" INTEGER NOT NULL,
    "LAST_SENT_TO_SERVER" INTEGER NULL
);

INSERT INTO PASS (TAG_ID, PASS_TIME, BARRIER_ID, LAST_SENT_TO_SERVER)
VALUES ('E4F0F695', DATETIME('now', 'localtime'), 3, DATETIME('now', 'localtime'))